<?php
/**
 * Eventsky plugin for Craft CMS 3.x
 *
 * Craft plugin for event management and attendee registration
 *
 * @link      https://fredmansky.at
 * @copyright Copyright (c) 2021 Fredmansky
 */

namespace fredmansky\eventsky\elements;

use Craft;
use craft\base\Element;
use craft\elements\db\ElementQueryInterface;
use fredmansky\eventsky\elements\db\TicketQuery;
use fredmanskyeventsky\eventsky\records\TicketRecord;

class Ticket extends Element
{
    // Public Properties
    // =========================================================================

    /**
     * @var int EventId
     */
    public $eventId;

    /**
     * @var string Unique id for a ticket
     */
    public $ticketId;

    public $ticketType;

    // Static Methods
    // =========================================================================

    /**
     * Returns the display name of this class.
     *
     * @return string The display name of this class.
     */
    public static function displayName(): string
    {
        return Craft::t('eventsky', 'translate.elements.Ticket.displayName');
    }

    public static function pluralDisplayName(): string
    {
        return Craft::t('eventsky', 'translate.elements.Ticket.pluralDisplayName');
    }

    /**
     * @return ElementQueryInterface
     */
    public static function find(): ElementQueryInterface
    {
        return new TicketQuery(static::class);
    }

    /**
     * @param bool $isNew
     *
     * @return void
     */
    public function afterSave(bool $isNew)
    {
        if ($isNew) {
            $ticketRecord = new TicketRecord();
            $ticketRecord->id = $this->id;
        } else {
            $ticketRecord = TicketRecord::findOne($this->id);
        }

        if ($ticketRecord) {
            $ticketRecord->ticketId = $this->ticketId;
            $ticketRecord->eventId = $this->eventId;
            $ticketRecord->ticketType = $this->ticketType;

            $ticketRecord->save(false);
        }

        parent::afterSave($isNew); // TODO: Change the autogenerated stub
    }
}
